// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ep_ordinal
Rcpp::List ep_ordinal(const arma::vec& Y, const arma::mat& X, const arma::vec& alpha, const arma::vec& mu0, const arma::mat& S0, const arma::mat& Q0, const int maxit, const double tresh, const bool verbose, const bool full_out);
RcppExport SEXP _viord_ep_ordinal(SEXP YSEXP, SEXP XSEXP, SEXP alphaSEXP, SEXP mu0SEXP, SEXP S0SEXP, SEXP Q0SEXP, SEXP maxitSEXP, SEXP treshSEXP, SEXP verboseSEXP, SEXP full_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q0(Q0SEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type tresh(treshSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const bool >::type full_out(full_outSEXP);
    rcpp_result_gen = Rcpp::wrap(ep_ordinal(Y, X, alpha, mu0, S0, Q0, maxit, tresh, verbose, full_out));
    return rcpp_result_gen;
END_RCPP
}
// vb_ordinal
Rcpp::List vb_ordinal(const arma::vec& Y, const arma::mat& X, const arma::vec& alpha, const arma::vec& mu0, const arma::mat& S0, const arma::mat& Q0, const int maxit, const double tresh, const bool verbose, const bool full_out);
RcppExport SEXP _viord_vb_ordinal(SEXP YSEXP, SEXP XSEXP, SEXP alphaSEXP, SEXP mu0SEXP, SEXP S0SEXP, SEXP Q0SEXP, SEXP maxitSEXP, SEXP treshSEXP, SEXP verboseSEXP, SEXP full_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q0(Q0SEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type tresh(treshSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const bool >::type full_out(full_outSEXP);
    rcpp_result_gen = Rcpp::wrap(vb_ordinal(Y, X, alpha, mu0, S0, Q0, maxit, tresh, verbose, full_out));
    return rcpp_result_gen;
END_RCPP
}
// pmf_ordinal
Rcpp::List pmf_ordinal(const arma::vec& Y, const arma::mat& X, const arma::vec& alpha, const arma::vec& mu0, const arma::mat& S0, const arma::mat& Q0, const int maxit, const double tresh, const bool verbose, const bool full_out);
RcppExport SEXP _viord_pmf_ordinal(SEXP YSEXP, SEXP XSEXP, SEXP alphaSEXP, SEXP mu0SEXP, SEXP S0SEXP, SEXP Q0SEXP, SEXP maxitSEXP, SEXP treshSEXP, SEXP verboseSEXP, SEXP full_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S0(S0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q0(Q0SEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type tresh(treshSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const bool >::type full_out(full_outSEXP);
    rcpp_result_gen = Rcpp::wrap(pmf_ordinal(Y, X, alpha, mu0, S0, Q0, maxit, tresh, verbose, full_out));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_viord_ep_ordinal", (DL_FUNC) &_viord_ep_ordinal, 10},
    {"_viord_vb_ordinal", (DL_FUNC) &_viord_vb_ordinal, 10},
    {"_viord_pmf_ordinal", (DL_FUNC) &_viord_pmf_ordinal, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_viord(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
