# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ep_ordinal <- function(Y, X, alpha, mu0, S0, Q0, maxit = 100L, tresh = 1e-6, verbose = FALSE, full_out = FALSE) {
    .Call('_viord_ep_ordinal', PACKAGE = 'viord', Y, X, alpha, mu0, S0, Q0, maxit, tresh, verbose, full_out)
}

vb_ordinal <- function(Y, X, alpha, mu0, S0, Q0, maxit = 100L, tresh = 1e-6, verbose = FALSE, full_out = FALSE) {
    .Call('_viord_vb_ordinal', PACKAGE = 'viord', Y, X, alpha, mu0, S0, Q0, maxit, tresh, verbose, full_out)
}

pmf_ordinal <- function(Y, X, alpha, mu0, S0, Q0, maxit = 100L, tresh = 1e-6, verbose = FALSE, full_out = FALSE) {
    .Call('_viord_pmf_ordinal', PACKAGE = 'viord', Y, X, alpha, mu0, S0, Q0, maxit, tresh, verbose, full_out)
}

